server:
    servlet:
      context-path: /appDSDRegMarcasApi
      session:
        timeout: 300

spring: 
  profiles:
      active: 'dev'
  banner:    location: classpath:/conf/banner.txt
      
    
logging:
  config: classpath:logback.xml 
    